AllCops:
  TargetRubyVersion: 2.2

Metrics/LineLength:
  IgnoredPatterns:
    - '^Given'
    - '^When'
    - '^Then'

Documentation:
  Enabled: false

AccessorMethodName:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

BlockLength:
  Exclude:
    - './spec/**/*_spec.rb'
    - 'site_prism.gemspec'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true

# https://github.com/rubocop-hq/rubocop/issues/5953
Style/AccessModifierDeclarations:
  Enabled: false

# https://github.com/rubocop-hq/rubocop/issues/6084
# https://github.com/rubocop-hq/rubocop/issues/6349
Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional
