AllCops:
  TargetRubyVersion: 2.2

Documentation:
  Enabled: false

AccessorMethodName:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

BlockLength:
  Exclude:
    - './spec/*_spec.rb'
    - 'site_prism.gemspec'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true
